
'use client'
import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import UserLoader from "./components/UserLoader";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="he" dir="rtl">
<head>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
  <link
    href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300..700&family=Rubik:wght@300..900&display=swap"
    rel="stylesheet"
  />
</head>

<body>
  
        <SessionProvider>
        {/* <UserLoader />  */}
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
